version: '3.3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./tubearchivist/youtube:/media/youtube:ro  # note :ro at the end
  tubearchivist-jf:
    image: bbilly1/tubearchivist-jf
    container_name: tubearchivist-jf
    environment:
      - TA_URL=http://tubearchivist:8000
      - TA_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - JF_URL=http://jellyfin:8096
      - JF_TOKEN=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    volumes:
      - ./tubearchivist/youtube:/youtube  # matching youtube volume as in Tube Archivist
    expose:
      - "8001"
